// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrfadmlmvfkzrfswyaza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhyZmFkbWxtdmZrenJmc3d5YXphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU2Njg5NTAsImV4cCI6MjA5MTI0NDk1MH0.bX7eLAvUCQyTI79erZFi30rTc9n_WNthIDfWApTgf-c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});